# Generated by Django 5.1.1 on 2024-09-28 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "autor",
                "verbose_name_plural": "autores",
            },
        ),
        migrations.CreateModel(
            name="cdd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "cdd",
            },
        ),
        migrations.CreateModel(
            name="leitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("data_nascimento", models.DateField()),
            ],
            options={
                "verbose_name": "leitor",
                "verbose_name_plural": "leitores",
            },
        ),
        migrations.CreateModel(
            name="livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("edicao", models.IntegerField()),
                ("quantidade", models.IntegerField()),
                ("volume", models.IntegerField()),
                (
                    "cdd",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biblioteca.autor",
                    ),
                ),
            ],
            options={
                "verbose_name": "livro",
                "verbose_name_plural": "livros",
            },
        ),
        migrations.CreateModel(
            name="emprestimo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_emprestimo", models.DateField()),
                ("data_devolucao", models.DateField()),
                ("devolvido", models.BooleanField()),
                (
                    "leitor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biblioteca.leitor",
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biblioteca.livro",
                    ),
                ),
            ],
            options={
                "verbose_name": "emprestimo",
                "verbose_name_plural": "emprestimos",
            },
        ),
        migrations.CreateModel(
            name="livro_tem_autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "autor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biblioteca.autor",
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="biblioteca.livro",
                    ),
                ),
            ],
            options={
                "verbose_name": "livro_tem_autor",
                "verbose_name_plural": "livro_tem_autores",
            },
        ),
    ]
