# Generated by Django 5.1.1 on 2024-09-29 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0003_rename_livro_emprestimo_exemplar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livro",
            name="quantidade",
        ),
    ]
