# Generated by Django 5.1.1 on 2024-09-29 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("biblioteca", "0004_remove_livro_quantidade"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Livro_tem_autor",
            new_name="LivroTemAutor",
        ),
    ]
